/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public\models\cumulart.glb -o src\components\scenes\cumulart.tsx -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, Float } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Column_Round1: THREE.Mesh
    Column_Round2: THREE.Mesh
    Column_Round3: THREE.Mesh
    Column_SquareBig: THREE.Mesh
    Column_SquareSmall: THREE.Mesh
    Shelf_Large: THREE.Mesh
    Painting_1: THREE.Mesh
    Painting_2: THREE.Mesh
    Painting001_1: THREE.Mesh
    Painting001_2: THREE.Mesh
    Phone_1: THREE.Mesh
    Phone_2: THREE.Mesh
    Phone_3: THREE.Mesh
    Houseplant_5_1: THREE.Mesh
    Houseplant_5_2: THREE.Mesh
    Houseplant_5_3: THREE.Mesh
    Houseplant_6_1: THREE.Mesh
    Houseplant_6_2: THREE.Mesh
    Houseplant_6_3: THREE.Mesh
    Houseplant_7_1: THREE.Mesh
    Houseplant_7_2: THREE.Mesh
    Houseplant_7_3: THREE.Mesh
  }
  materials: {
    Marble: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    Plant_Green: THREE.MeshStandardMaterial
    ['Grey.009']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Cumulart(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cumulart.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <ambientLight intensity={1} />
      <directionalLight position={[0, 10, 0]} intensity={4} />
      <PerspectiveCamera makeDefault={true} far={1000} near={0.1} fov={22.895} position={[15.236, 7.892, -7.724]} rotation={[-2.612, 1.2, 2.642]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0, -0.346, 0]} />
      <Float>
      <mesh geometry={nodes.Column_Round1.geometry} material={materials.Marble} position={[-5.108, 0, 2.878]} rotation={[0, 1.055, 0]} />
      </Float>
      <Float>
        <mesh geometry={nodes.Column_Round3.geometry} material={materials.Marble} position={[-6.784, 0, -6.22]} />
      </Float>
      <Float>
        <mesh geometry={nodes.Column_SquareBig.geometry} material={materials.Marble} position={[-10.602, 0, 10.493]} />
      </Float>
      <mesh geometry={nodes.Column_Round2.geometry} material={materials.Marble} position={[-15.47, 3.264, 6.214]} rotation={[0.348, 0.017, -0.017]} />
      <Float>
      <mesh geometry={nodes.Column_SquareSmall.geometry} material={materials.Marble} position={[-14.077, 3.831, 0.302]} rotation={[2.025, 1.238, -2.605]} />
      </Float>
      <mesh geometry={nodes.Shelf_Large.geometry} material={materials.White} position={[-9.866, 0, -0.366]} rotation={[0, Math.PI / 2, 0]} />
      <Float>
      <group position={[-10.058, 3.055, 5.099]} rotation={[-0.138, 0.641, 0.149]}>
        <mesh geometry={nodes.Painting_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Painting_2.geometry} material={materials.Red} />
      </group>
      </Float>
      <Float>
      <group position={[-10.783, 2.758, -3.048]} rotation={[0.266, -0.467, 0.323]}>
        <mesh geometry={nodes.Painting001_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Painting001_2.geometry} material={materials['Material.001']} />
      </group>
      </Float>
      <Float>
      <group position={[0.548, 4.131, -2.188]} rotation={[0.402, 0.184, 0.05]}>
        <mesh geometry={nodes.Phone_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Phone_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Phone_3.geometry} material={materials['Material.003']} />
      </group>
      </Float>
      <group position={[-5.082, 1.785, 2.887]}>
        <mesh geometry={nodes.Houseplant_5_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Houseplant_5_2.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Houseplant_5_3.geometry} material={materials.Plant_Green} />
      </group>
      <Float>
      <group position={[-5.443, 2.208, 5.868]} rotation={[2.781, 0.548, 2.741]}>
        <mesh geometry={nodes.Houseplant_6_1.geometry} material={materials['Grey.009']} />
        <mesh geometry={nodes.Houseplant_6_2.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Houseplant_6_3.geometry} material={materials.Plant_Green} />
      </group>
      </Float>
      <group position={[-9.887, 4.408, 0.027]}>
        <mesh geometry={nodes.Houseplant_7_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Houseplant_7_2.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Houseplant_7_3.geometry} material={materials.Plant_Green} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cumulart.glb')
